"""Build js/data.js from checked hospital coordinates and the race route."""
import json
import re
from pathlib import Path

from id_copy import ADDRESSES, FINISH, NAMES, NOTES, SEGMENTS, START

ROOT = Path(__file__).resolve().parents[1]
route = json.loads((Path(__file__).resolve().parent / "route-latlon.json").read_text())

places = []


def pair(en, id_text=None):
    return {"en": en, "id": en if id_text is None else id_text}


def hours_id(hours):
    if hours == "24 hours":
        return "24 jam"
    return hours


def add(**item):
    phone = item.get("phone") or ""
    digits = re.sub(r"\D", "", phone)
    tel = ""
    if digits:
        if digits.startswith("0"):
            digits = "62" + digits[1:]
        tel = "+" + digits
    place_id = item["id"]
    if place_id not in NOTES:
        raise SystemExit(f"Missing Indonesian note: {place_id}")
    hours = item.get("hours") or ""
    item["phone"] = phone
    item["tel"] = tel
    item["name"] = pair(item["name"], NAMES.get(place_id))
    item["address"] = pair(item["address"], ADDRESSES.get(place_id))
    item["hours"] = pair(hours, hours_id(hours))
    item["note"] = pair(item["note"], NOTES[place_id])
    lat, lng = item["lat"], item["lng"]
    if not (-7.05 < lat < -6.15 and 106.7 < lng < 107.7):
        raise SystemExit(f"Coordinate out of corridor: {place_id} {lat},{lng}")
    places.append(item)


# --- Jakarta to Bogor. Race enters via Pasar Minggu, not Kramat Jati. ---
add(
    id="pasar-minggu",
    name="RSUD Pasar Minggu",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-50866999",
    address="Jl. TB Simatupang No. 1, Ragunan",
    km="",
    lat=-6.293984,
    lng=106.819869,
    note="Large public hospital at the south-Jakarta start of this corridor.",
)
add(
    id="jagakarsa",
    name="RSUD Jagakarsa",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Moh. Kahfi I, Jagakarsa",
    km="",
    lat=-6.316176,
    lng=106.811363,
    note="About 2 km off Jl. TB Simatupang. No phone in the crew notes.",
)
add(
    id="pasar-rebo",
    name="RSUD Pasar Rebo",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8401127",
    address="Jl. TB Simatupang No. 30",
    km="",
    lat=-6.303647,
    lng=106.862196,
    note="Sits just before the turn onto Jl. Raya Bogor. One of the larger emergency rooms on the Jakarta stretch.",
)
add(
    id="binawaluya",
    name="RS Jantung Binawaluya",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-87781605",
    address="Jl. TB Simatupang No. 71, Ciracas",
    km="",
    lat=-6.307958,
    lng=106.870872,
    note="Heart hospital. The crew notes warn that its Google Maps pin is sometimes wrong.",
)
add(
    id="restu-kasih",
    name="RS Restu Kasih",
    segment="jakarta",
    side="detour",
    kind="rsia",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8001177",
    address="Jl. Raya Bogor, Kramat Jati",
    km="KM 19",
    lat=-6.265707,
    lng=106.866471,
    note="Mother-and-child hospital. North of the Pasar Rebo junction, so the race route misses it if you join Jl. Raya Bogor from Pasar Rebo.",
)
add(
    id="rs-polri",
    name="RS Polri (Bhayangkara Tk. I Said Sukanto)",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. RS Polri, Kramat Jati",
    km="KM 19–20",
    lat=-6.269462,
    lng=106.870714,
    note="Major trauma-capable emergency room. Same northern approach as Restu Kasih: not passed when entering from Pasar Rebo. No phone in the crew notes.",
)
add(
    id="pusdikkes",
    name="RS Pusdikkes TNI AD",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8092358",
    address="Jl. Raya Bogor, Kramat Jati",
    km="KM 20",
    lat=-6.276312,
    lng=106.869277,
    note="Army medical education center with a hospital. Not passed when entering from Pasar Rebo.",
)
add(
    id="kramat-jati",
    name="RSUD Kramat Jati",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Raya Inpres, Kramat Jati",
    km="",
    lat=-6.286868,
    lng=106.862280,
    note="Short detour off Jl. Raya Bogor. No phone in the crew notes.",
)
add(
    id="al-fauzan",
    name="RSIA Al-Fauzan",
    segment="jakarta",
    side="detour",
    kind="rsia",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Kramat Jati",
    km="",
    lat=-6.299599,
    lng=106.869086,
    note="Crew notes call this a mother-and-child hospital. OpenStreetMap lists the building as RSU Al Fauzan. No phone in the crew notes.",
)
add(
    id="harapan-bunda",
    name="RS Harapan Bunda",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8400257",
    address="Jl. Raya Bogor No. 44, Rambutan, Ciracas",
    km="",
    lat=-6.303027,
    lng=106.868051,
    note="Just past the Pasar Rebo junction, on the way south.",
)
add(
    id="tjakra",
    name="Klinik / RB Tjakra",
    segment="jakarta",
    side="road",
    kind="clinic",
    major_er=False,
    open24=False,
    hours="08:00–20:30",
    exact=True,
    phone="",
    address="Jl. Raya Bogor, Susukan",
    km="KM 24",
    lat=-6.314855,
    lng=106.863513,
    note="Maternity clinic, not a full hospital. Closed overnight.",
)
add(
    id="tugu-ibu",
    name="RS Tugu Ibu",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8710870",
    address="Jl. Raya Bogor KM 29, Mekarsari, Cimanggis",
    km="KM 29",
    lat=-6.356489,
    lng=106.860494,
    note="Depok. On Jl. Raya Bogor.",
)
add(
    id="setya-bhakti",
    name="RSIA Setya Bhakti",
    segment="jakarta",
    side="road",
    kind="rsia",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8711518",
    address="Jl. Raya Bogor KM 30, Mekarsari, Cimanggis",
    km="KM 30",
    lat=-6.368373,
    lng=106.860408,
    note="Mother-and-child hospital.",
)
add(
    id="tumbuh-kembang",
    name="RSIA Tumbuh Kembang",
    segment="jakarta",
    side="road",
    kind="rsia",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Raya Bogor, Tugu, Cimanggis",
    km="KM 31",
    lat=-6.371676,
    lng=106.861428,
    note="Mother-and-child hospital. No phone in the crew notes.",
)
add(
    id="cisalak",
    name="RS Sentra Medika Cisalak",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8743790",
    address="Jl. Raya Bogor, Cisalak",
    km="KM 33",
    lat=-6.390969,
    lng=106.865275,
    note="One of the larger emergency rooms between Jakarta and Bogor.",
)
add(
    id="simpangan",
    name="RS Simpangan Depok",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8741549",
    address="Jl. Raya Bogor No. 36, Sukamaju, Cilodong",
    km="",
    lat=-6.408780,
    lng=106.861693,
    note="On Jl. Raya Bogor.",
)
add(
    id="primaya",
    name="Primaya Hospital Depok",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. H. Dimun, behind RS Simpangan",
    km="",
    lat=-6.407686,
    lng=106.851012,
    note="Short detour behind RS Simpangan. No phone in the crew notes.",
)
add(
    id="trimitra",
    name="RS Trimitra",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8763055",
    address="Jl. Raya Bogor, Pabuaran, Cibinong",
    km="KM 43",
    lat=-6.474530,
    lng=106.847265,
    note="Kabupaten Bogor, still on Jl. Raya Bogor.",
)
add(
    id="bina-husada",
    name="Mitra Keluarga Cibinong (Bina Husada)",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Mayor Oking, Cibinong",
    km="",
    lat=-6.473037,
    lng=106.863626,
    note="The crew notes pair Bina Husada with Mitra Keluarga, both off the main road on Jl. Mayor Oking. OpenStreetMap still labels this building Bina Husada. No phone in the crew notes.",
)
add(
    id="sentra-cibinong",
    name="RS Sentra Medika Cibinong",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Mayor Oking, Cibinong",
    km="",
    lat=-6.480687,
    lng=106.864991,
    note="Same side street as Mitra Keluarga / Bina Husada. No phone in the crew notes.",
)
add(
    id="rsud-cibinong",
    name="RSUD Cibinong",
    segment="jakarta",
    side="detour",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. KSR Dadi Kusmayadi No. 27, Cibinong",
    km="",
    lat=-6.472985,
    lng=106.830064,
    note="Large emergency room, a short way off Jl. Raya Bogor. No phone in the crew notes. The hospital website lists 021-8753487.",
)
add(
    id="assalam",
    name="RS Assalam",
    segment="jakarta",
    side="road",
    kind="rsia",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="021-8753724",
    address="Nanggewer Mekar, Cibinong",
    km="KM 46.7",
    lat=-6.500206,
    lng=106.843365,
    note="OpenStreetMap lists this building as RSIA Assalam.",
)
add(
    id="azra",
    name="RS Azra",
    segment="jakarta",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0251-6900420",
    address="Jl. Pajajaran No. 219, Bogor",
    km="",
    lat=-6.579170,
    lng=106.807772,
    note="Where Jl. Raya Bogor ends at Warung Jambu. One of the larger emergency rooms before the Puncak climb.",
)

# --- Bogor to Cianjur ---
add(
    id="ciawi",
    name="RSUD Ciawi (Dr. K.H. Idham Chalid)",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0251-8240797",
    address="Jl. Raya Puncak No. 479, Ciawi",
    km="",
    lat=-6.660367,
    lng=106.853115,
    note="Largest general hospital before the Puncak climb.",
)
add(
    id="rspg",
    name="RS Paru Dr. M. Goenawan Partowidigdo",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0251-8253630",
    address="Jl. Raya Puncak, Cibeureum, Cisarua",
    km="KM 83",
    lat=-6.688213,
    lng=106.939556,
    note="Ministry of Health lung hospital. The emergency room also takes general cases.",
)
add(
    id="as-shifa",
    name="Klinik As-Shifa Tugu",
    segment="puncak",
    side="road",
    kind="clinic",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0251-8252888",
    address="Jl. Raya Puncak KM 84, Leuwimalang, Tugu Utara",
    km="KM 84",
    lat=-6.685695,
    lng=106.955900,
    note="Clinic, not a hospital. Last stop for first aid before the pass. The pin is the mapped Klinik Tugu at KM 84, which matches the As-Shifa listing and this phone.",
)
add(
    id="gap-puncak",
    name="No hospital: Puncak Pass",
    segment="puncak",
    side="road",
    kind="gap",
    major_er=False,
    open24=False,
    hours="",
    exact=True,
    phone="",
    address="Tugu Utara to Cipanas",
    km="",
    lat=-6.705015,
    lng=106.994000,
    note="The longest stretch without a hospital. The road crosses Puncak Pass and Gunung Mas. Next referral is RSUD Cimacan in Cipanas.",
)
add(
    id="hanjawar",
    name="RS Hanjawar",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0263-2951443",
    address="Jl. Hanjawar No. 127B, Cimacan, Cipanas",
    km="",
    lat=-6.712338,
    lng=107.021172,
    note="Small hospital. The crew notes say reviews are poor. The pin is the published map point for this phone. The earlier estimate was the midwife clinic at KM 86, a different building.",
)
add(
    id="cimacan",
    name="RSUD Cimacan",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Raya Cimacan No. 17A, Cipanas",
    km="",
    lat=-6.721763,
    lng=107.033369,
    note="Main referral for north Cianjur. Emergency room is 24 hours. The pin is the road beside the hospital. No phone in the crew notes.",
)
add(
    id="sayang",
    name="RSUD Sayang Cianjur",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0263-261026",
    address="Jl. Rumah Sakit No. 1, Cianjur",
    km="",
    lat=-6.809971,
    lng=107.140994,
    note="Class B. Largest referral hospital in Cianjur.",
)
add(
    id="bhayangkara-cianjur",
    name="RS Bhayangkara Cianjur",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0263-285299",
    address="Jl. Suroso No. 21, Cianjur",
    km="",
    lat=-6.818942,
    lng=107.140597,
    note="Police hospital in Cianjur city. OpenStreetMap places it on Jl. Taifur Yusuf.",
)
add(
    id="hasna",
    name="Klinik Jantung Hasna Medika",
    segment="puncak",
    side="road",
    kind="clinic",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0263-5681741",
    address="Jl. Raya Bandung, Bojong, Karangtengah",
    km="",
    lat=-6.80769,
    lng=107.156068,
    note="Heart clinic, not a general hospital.",
)
add(
    id="edelweiss",
    name="RS Edelweiss Bentang Salapan",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0263-5600999",
    address="Jl. Raya Bandung KM 17, Bojong, Karangtengah",
    km="KM 17",
    lat=-6.803138,
    lng=107.171578,
    note="General hospital on Jl. Nasional III. The crew notes name the road; the hospital's own address is KM 17 in Desa Bojong. The pin is that published map point, beside the road.",
)
add(
    id="hafiz",
    name="RS Dr. Hafiz (RSDH)",
    segment="puncak",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0263-2910000",
    address="Jl. Pramuka No. 15, Karangtengah",
    km="",
    lat=-6.797953,
    lng=107.174813,
    note="General hospital at the east edge of Cianjur, where the Padalarang road begins.",
)

# --- Cianjur to Padalarang. Thin stretch. ---
add(
    id="tungturunan",
    name="RB Tungturunan / Klinik Bidan Ajeng",
    segment="cianjur",
    side="road",
    kind="clinic",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Selajambe No. 1, Hegarmanah, Sukaluyu",
    km="",
    lat=-6.810301,
    lng=107.233345,
    note="Maternity home, not a hospital. Published map point on Jl. Selajambe, about 350 m off the Cianjur–Ciranjang road. No phone in the crew notes.",
)
add(
    id="ciranjang",
    name="Puskesmas Rawat Inap Ciranjang",
    segment="cianjur",
    side="road",
    kind="puskesmas",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0263-322306",
    address="Jl. Rumah Sakit No. 194, Ciranjang",
    km="",
    lat=-6.813966,
    lng=107.244307,
    note="Open overnight, but set back from the main road.",
)
add(
    id="citra-insani",
    name="Klinik Citra Insani Husada",
    segment="cianjur",
    side="road",
    kind="clinic",
    major_er=False,
    open24=False,
    hours="07:00–21:00",
    exact=False,
    phone="022-6903108",
    address="Rajamandala Kulon",
    km="",
    lat=-6.832706,
    lng=107.351221,
    note="Inpatient primary clinic. Closed overnight. An old clinic notice gives Kp. Ciburahol No. 41 in Rajamandala Kulon. A map point about 1.4 km north of the road was not confirmed as that building, so the pin stays on the Rajamandala Kulon road.",
)
add(
    id="rajamandala",
    name="Puskesmas DTP Rajamandala",
    segment="cianjur",
    side="road",
    kind="puskesmas",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=False,
    phone="",
    address="Jl. Raya Cipatat, Rajamandala",
    km="",
    lat=-6.832630,
    lng=107.348734,
    note="Crew notes describe a 24-hour puskesmas on Jl. Raya Cipatat. This pin is still the mapped puskesmas pembantu in Rajamandala Kulon. A directory lists Jl. Raya Cipatat No. 1, but no separate building coordinate was found.",
)
add(
    id="rahmani",
    name="Klinik Rahmani Medical",
    segment="cianjur",
    side="road",
    kind="clinic",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=False,
    phone="",
    address="Jl. Raya Cipatat KM 32 No. 25, Cipatat",
    km="KM 32",
    lat=-6.824371,
    lng=107.383934,
    note="Open overnight. The pin is a published map point for KM 32 on Jl. Raya Cipatat. OpenStreetMap does not name the building, so confirm the gate.",
)
add(
    id="gap-citatah",
    name="No general hospital: Cipatat cliffs",
    segment="cianjur",
    side="road",
    kind="gap",
    major_er=False,
    open24=False,
    hours="",
    exact=True,
    phone="",
    address="Sukaluyu to Citatah",
    km="",
    lat=-6.825,
    lng=107.420,
    note="About 40 km from Sukaluyu to Citatah with no general hospital, including the limestone cliffs between Cipatat and Citatah. Only a maternity home, puskesmas, and clinics. Next general hospitals are in Padalarang.",
)
add(
    id="kartini",
    name="RSIA Kartini Padalarang",
    segment="cianjur",
    side="road",
    kind="rsia",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Letkol G.A. Manulang No. 46, Padalarang",
    km="",
    lat=-6.843775,
    lng=107.480389,
    note="Mother-and-child hospital in Padalarang town. No phone in the crew notes.",
)
add(
    id="graha-medika",
    name="Graha Medika Padalarang",
    segment="cianjur",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Raya Padalarang, Komplek Padalarang Point",
    km="",
    lat=-6.844625,
    lng=107.486268,
    note="In Padalarang town. No phone in the crew notes.",
)
add(
    id="cahya",
    name="RS Cahya Kawaluyan",
    segment="cianjur",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Parahyangan Raya, near the Padalarang toll exit",
    km="KM 3",
    lat=-6.865514,
    lng=107.473805,
    note="Large general hospital south of Padalarang town, toward Kota Baru Parahyangan. Useful if you are already near the toll exit. No phone in the crew notes.",
)
add(
    id="parahyangan",
    name="Parahyangan Hospital",
    segment="cianjur",
    side="road",
    kind="rsia",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="022-86808000",
    address="Kota Baru Parahyangan",
    km="",
    lat=-6.866317,
    lng=107.463391,
    note="Mother-and-child hospital in Kota Baru Parahyangan, south of the town road.",
)

# --- Padalarang to Cimahi / Cibeureum ---
add(
    id="karisma",
    name="RS Karisma Cimareme",
    segment="cimahi",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0831-1464-6747",
    address="Jl. Raya Cimareme No. 235",
    km="",
    lat=-6.863328,
    lng=107.502970,
    note="Near the Padalarang toll exit, on the road into Cimahi.",
)
add(
    id="imc",
    name="RS IMC Cimareme",
    segment="cimahi",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="0857-8555-5170",
    address="Jl. Raya Gadobangkong No. 173",
    km="",
    lat=-6.863180,
    lng=107.510206,
    note="OpenStreetMap names this building Rumah Sakit Indra Medical, on Jl. Raya Gadobangkong.",
)
add(
    id="cibabat",
    name="RSUD Cibabat",
    segment="cimahi",
    side="road",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="022-6652025",
    address="Jl. Jenderal H. Amir Machmud No. 140, Cimahi",
    km="",
    lat=-6.879680,
    lng=107.550360,
    note="Cimahi city hospital. One of the two largest emergency rooms on this stretch. Pin is the stop on Jl. Amir Machmud in front of the hospital.",
)
add(
    id="mitra-kasih",
    name="RS Mitra Kasih",
    segment="cimahi",
    side="road",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="022-6652774",
    address="Jl. Jenderal H. Amir Machmud No. 341, Cimahi",
    km="",
    lat=-6.884251,
    lng=107.552773,
    note="On the same road as RSUD Cibabat, further toward Cibeureum.",
)
add(
    id="dustira",
    name="RS Tk. II Dustira",
    segment="cimahi",
    side="detour",
    kind="hospital",
    major_er=True,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="022-6652207",
    address="Jl. Dustira No. 1, Baros, Cimahi",
    km="",
    lat=-6.886595,
    lng=107.534231,
    note="Large army hospital, about 1–2 km off Jl. Amir Machmud. Main emergency referral in Cimahi, together with RSUD Cibabat.",
)
add(
    id="baros",
    name="RSU Baros",
    segment="cimahi",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Baros, Cimahi Tengah",
    km="",
    lat=-6.891446,
    lng=107.536899,
    note="Short detour. No phone in the crew notes.",
)
add(
    id="kasih-bunda",
    name="RSU Kasih Bunda",
    segment="cimahi",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="022-6614221",
    address="Jl. Mahar Martanegara No. 166, Cimahi",
    km="",
    lat=-6.900240,
    lng=107.547196,
    note="About 1–2 km off the main road.",
)
add(
    id="mitra-anugrah",
    name="RS Mitra Anugrah Lestari",
    segment="cimahi",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="022-6027204",
    address="Jl. Cibaligo No. 76, near Cibeureum",
    km="",
    lat=-6.900778,
    lng=107.555696,
    note="Close to Cibeureum, just off Jl. Amir Machmud.",
)
add(
    id="cibeureum",
    name="Puskesmas Cibeureum",
    segment="cimahi",
    side="road",
    kind="puskesmas",
    major_er=False,
    open24=False,
    hours="07:30–14:30",
    exact=True,
    phone="",
    address="Jl. Jenderal H. Amir Machmud No. 126, Cibeureum",
    km="",
    lat=-6.900583,
    lng=107.562561,
    note="Puskesmas, not a hospital. Daytime only. Do not count on it during the night legs.",
)
add(
    id="avisena",
    name="RSU Avisena",
    segment="cimahi",
    side="detour",
    kind="hospital",
    major_er=False,
    open24=True,
    hours="24 hours",
    exact=True,
    phone="",
    address="Jl. Melong No. 170, Cimahi Selatan",
    km="",
    lat=-6.921782,
    lng=107.555953,
    note="South of Cibeureum, toward the Bandung approach. No phone in the crew notes.",
)

segments = [
    {
        "id": "jakarta",
        "label": pair("Jakarta → Bogor"),
        "blurb": pair(
            "Pasar Minggu and Jl. TB Simatupang, then Jl. Raya Bogor through Depok and Cibinong. Kramat Jati hospitals sit north of the Pasar Rebo junction and are missed on this entry.",
            SEGMENTS["jakarta"],
        ),
    },
    {
        "id": "puncak",
        "label": pair("Bogor → Cianjur"),
        "blurb": pair(
            "Ciawi, the Puncak climb, then Cipanas and Cianjur. There is no hospital between Tugu Utara and Cipanas.",
            SEGMENTS["puncak"],
        ),
    },
    {
        "id": "cianjur",
        "label": pair("Cianjur → Padalarang"),
        "blurb": pair(
            "A thin stretch. About 40 km from Sukaluyu to Citatah has no general hospital, only a maternity home, puskesmas, and clinics.",
            SEGMENTS["cianjur"],
        ),
    },
    {
        "id": "cimahi",
        "label": pair("Padalarang → Bandung"),
        "blurb": pair(
            "Through Cimareme and Cimahi on Jl. Amir Machmud to Cibeureum. Largest emergency rooms here are RS Dustira and RSUD Cibabat.",
            SEGMENTS["cimahi"],
        ),
    },
]

guide = {
    "routeKm": 177.9,
    "route": route,
    "start": {
        "name": pair("Start", START["name"]),
        "detail": pair(
            "Kemdiktisaintek, Jakarta",
            "Kementerian Pendidikan Tinggi, Sains, dan Teknologi, Jakarta",
        ),
        "lat": -6.224047,
        "lng": 106.803681,
        "note": pair(
            "Start on the ITB Ultra Marathon 2026 map.",
            START["note"],
        ),
    },
    "finish": {
        "name": pair("Finish", FINISH["name"]),
        "detail": pair("Kampus ITB, Bandung"),
        "lat": -6.891030,
        "lng": 107.610244,
        "note": pair("Finish on the ITB Ultra Marathon 2026 map.", FINISH["note"]),
    },
    "segments": segments,
    "places": places,
}

out = ROOT / "js" / "data.js"
out.write_text("const GUIDE = " + json.dumps(guide, ensure_ascii=False, indent=2) + ";\n")
print(f"places {len(places)} route {len(route)} -> {out}")
